// Generated 2026-09-14 from valheim.weirdgloop.org (Food, Mead and item pages),
// cross-checked against the Valheim 1.0 patch notes. Edit by hand; regenerate only from the source table.
import type { Item } from './model.js';

export const ITEMS: Item[] = [
  { name: "Cooked boar meat", biome: "Meadows", recipe: { station: "Cooking station", yield: 1, materials: {"Boar meat": 1} }, food: { health: 30, stamina: 10, eitr: 0, healing: 2, duration: 1200 } },
  { name: "Cooked deer meat", biome: "Meadows", recipe: { station: "Cooking station", yield: 1, materials: {"Deer meat": 1} }, food: { health: 35, stamina: 12, eitr: 0, healing: 2, duration: 1200 } },
  { name: "Grilled neck tail", biome: "Meadows", recipe: { station: "Cooking station", yield: 1, materials: {"Neck tail": 1} }, food: { health: 25, stamina: 8, eitr: 0, healing: 2, duration: 1200 } },
  { name: "Honey", biome: "Meadows", source: "Beehive (Queen bee from abandoned houses)", food: { health: 8, stamina: 35, eitr: 0, healing: 1, duration: 900 } },
  { name: "Mushroom", biome: "Meadows", source: "Ground, also Black Forest", food: { health: 15, stamina: 15, eitr: 0, healing: 1, duration: 900 } },
  { name: "Raspberries", biome: "Meadows", source: "Bushes", food: { health: 7, stamina: 20, eitr: 0, healing: 1, duration: 600 } },
  { name: "Boar meat", biome: "Meadows", source: "Boar" },
  { name: "Dandelion", biome: "Meadows", source: "Ground" },
  { name: "Deer meat", biome: "Meadows", source: "Deer" },
  { name: "Feathers", biome: "Meadows", source: "Birds, chests" },
  { name: "Neck tail", biome: "Meadows", source: "Neck" },
  { name: "Perch", biome: "Meadows", source: "Fishing off Meadows and Black Forest coasts" },
  { name: "Blueberries", biome: "Black Forest", source: "Bushes", food: { health: 8, stamina: 25, eitr: 0, healing: 1, duration: 600 } },
  { name: "Boar jerky", biome: "Black Forest", recipe: { station: "Cauldron (1)", yield: 2, materials: {"Boar meat": 1, "Honey": 1} }, food: { health: 23, stamina: 23, eitr: 0, healing: 2, duration: 1800 } },
  { name: "Carrot", biome: "Black Forest", source: "Grow from Carrot seeds (ground)", food: { health: 10, stamina: 32, eitr: 0, healing: 1, duration: 900 } },
  { name: "Carrot soup", biome: "Black Forest", recipe: { station: "Cauldron (1)", yield: 1, materials: {"Mushroom": 1, "Carrot": 3} }, food: { health: 15, stamina: 45, eitr: 0, healing: 2, duration: 1500 } },
  { name: "Cooked bear meat", biome: "Black Forest", recipe: { station: "Cooking station", yield: 1, materials: {"Bear meat": 1} }, food: { health: 40, stamina: 13, eitr: 0, healing: 2, duration: 1200 } },
  { name: "Deer stew", biome: "Black Forest", recipe: { station: "Cauldron (1)", yield: 1, materials: {"Blueberries": 1, "Carrot": 1, "Cooked deer meat": 1} }, food: { health: 45, stamina: 15, eitr: 0, healing: 3, duration: 1500 } },
  { name: "Minced meat sauce", biome: "Black Forest", recipe: { station: "Cauldron (1)", yield: 1, materials: {"Boar meat": 1, "Neck tail": 1, "Carrot": 1} }, food: { health: 40, stamina: 13, eitr: 0, healing: 3, duration: 1500 } },
  { name: "Pulled Bear", biome: "Black Forest", recipe: { station: "Cauldron (1)", yield: 1, materials: {"Cooked bear meat": 1, "Carrot": 2, "Blueberries": 1} }, food: { health: 37, stamina: 16, eitr: 0, healing: 3, duration: 1800, unverified: "Wiki page is work in progress; healing per tick not listed, 3 taken from a guide." } },
  { name: "Queen's jam", biome: "Black Forest", recipe: { station: "Cauldron (1)", yield: 4, materials: {"Raspberries": 8, "Blueberries": 6} }, food: { health: 14, stamina: 40, eitr: 0, healing: 2, duration: 1200 } },
  { name: "Yellow mushroom", biome: "Black Forest", source: "Burial Chambers, Troll Caves, Sunken Crypts", food: { health: 10, stamina: 30, eitr: 0, healing: 1, duration: 600 } },
  { name: "Bear meat", biome: "Black Forest", source: "Bear" },
  { name: "Coal", biome: "Black Forest", source: "Charcoal kiln, or overcooked meat" },
  { name: "Greydwarf eye", biome: "Black Forest", source: "Greydwarf" },
  { name: "Raw fish", biome: "Black Forest", source: "Fishing (rod and bait from Haldor), any fish at the Food preparation table" },
  { name: "Thistle", biome: "Black Forest", source: "Ground, glows at night; also Swamp" },
  { name: "Trollfish", biome: "Black Forest", source: "Fishing off Black Forest coasts" },
  { name: "Minor healing mead", biome: "Black Forest", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Blueberries": 5, "Raspberries": 10, "Dandelion": 1} }, mead: { effect: "50 health over 10 s", duration: 10, cooldown: 120 } },
  { name: "Minor stamina mead", biome: "Black Forest", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Raspberries": 10, "Yellow mushroom": 10} }, mead: { effect: "80 stamina", duration: 2, cooldown: 120 } },
  { name: "Poison resistance mead", biome: "Black Forest", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Thistle": 5, "Neck tail": 1, "Coal": 10} }, mead: { effect: "Poison resistance", duration: 600, cooldown: 600 } },
  { name: "Tasty mead", biome: "Black Forest", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Raspberries": 10, "Blueberries": 5} }, mead: { effect: "+100 % stamina regen, -50 % health regen", duration: 10, cooldown: 10 } },
  { name: "Black Forest buffet platter", biome: "Swamp", recipe: { station: "Food preparation table", yield: 1, materials: {"Deer stew": 3, "Thistle": 5, "Queen's jam": 4, "Woodland herb blend": 1} }, food: { health: 35, stamina: 35, eitr: 0, healing: 3, duration: 3000, feast: true } },
  { name: "Black soup", biome: "Swamp", recipe: { station: "Cauldron (2)", yield: 1, materials: {"Bloodbag": 1, "Honey": 1, "Turnip": 1} }, food: { health: 50, stamina: 17, eitr: 0, healing: 3, duration: 1200 } },
  { name: "Cooked fish", biome: "Swamp", recipe: { station: "Cooking station", yield: 1, materials: {"Raw fish": 1} }, food: { health: 45, stamina: 15, eitr: 0, healing: 2, duration: 1200 } },
  { name: "Cooked serpent meat", biome: "Swamp", recipe: { station: "Iron cooking station", yield: 1, materials: {"Serpent meat": 1} }, food: { health: 70, stamina: 23, eitr: 0, healing: 3, duration: 1500 } },
  { name: "Muckshake", biome: "Swamp", recipe: { station: "Cauldron (2)", yield: 1, materials: {"Ooze": 1, "Raspberries": 2, "Blueberries": 2} }, food: { health: 16, stamina: 50, eitr: 0, healing: 1, duration: 1200 } },
  { name: "Sailor's bounty", biome: "Swamp", recipe: { station: "Food preparation table", yield: 1, materials: {"Cooked fish": 5, "Thistle": 4, "Cooked serpent meat": 2, "Seafarer's herbs": 1} }, food: { health: 45, stamina: 45, eitr: 0, healing: 3, duration: 3000, feast: true } },
  { name: "Sausages", biome: "Swamp", recipe: { station: "Cauldron (2)", yield: 4, materials: {"Entrails": 4, "Boar meat": 1, "Thistle": 1} }, food: { health: 55, stamina: 18, eitr: 0, healing: 3, duration: 1500 } },
  { name: "Serpent stew", biome: "Swamp", recipe: { station: "Cauldron (2)", yield: 1, materials: {"Mushroom": 1, "Cooked serpent meat": 1, "Honey": 2} }, food: { health: 80, stamina: 26, eitr: 0, healing: 4, duration: 1800 } },
  { name: "Swamp dweller's delight", biome: "Swamp", recipe: { station: "Food preparation table", yield: 1, materials: {"Sausages": 8, "Bloodbag": 4, "Turnip stew": 2, "Woodland herb blend": 1} }, food: { health: 35, stamina: 35, eitr: 0, healing: 3, duration: 3000, feast: true } },
  { name: "Turnip stew", biome: "Swamp", recipe: { station: "Cauldron (2)", yield: 1, materials: {"Boar meat": 1, "Turnip": 3} }, food: { health: 18, stamina: 55, eitr: 0, healing: 2, duration: 1500 } },
  { name: "Whole roasted Meadow boar", biome: "Swamp", recipe: { station: "Food preparation table", yield: 1, materials: {"Cooked deer meat": 2, "Cooked boar meat": 5, "Dandelion": 4, "Woodland herb blend": 1} }, food: { health: 35, stamina: 35, eitr: 0, healing: 2, duration: 3000, feast: true } },
  { name: "Bloodbag", biome: "Swamp", source: "Leech" },
  { name: "Cured squirrel hamstring", biome: "Swamp", source: "The Bog Witch, 80 coins for 5" },
  { name: "Entrails", biome: "Swamp", source: "Draugr" },
  { name: "Fresh seaweed", biome: "Swamp", source: "The Bog Witch, 75 coins for 5" },
  { name: "Ooze", biome: "Swamp", source: "Blob, Oozer" },
  { name: "Powdered dragon eggshells", biome: "Swamp", source: "The Bog Witch, 120 coins for 5" },
  { name: "Pungent pebbles", biome: "Swamp", source: "The Bog Witch, 125 coins for 5" },
  { name: "Seafarer's herbs", biome: "Swamp", source: "The Bog Witch (coins)" },
  { name: "Serpent meat", biome: "Swamp", source: "Sea Serpent (ocean)" },
  { name: "Turnip", biome: "Swamp", source: "Grow from Turnip seeds (yellow flowers)" },
  { name: "Woodland herb blend", biome: "Swamp", source: "The Bog Witch, 120 coins for 5, after The Elder" },
  { name: "Draught of Vananidir", biome: "Swamp", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Dandelion": 10, "Perch": 2, "Fresh seaweed": 1} }, mead: { effect: "-50 % swimming stamina use", duration: 300, cooldown: 0 } },
  { name: "Frost resistance mead", biome: "Swamp", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Thistle": 5, "Bloodbag": 2, "Greydwarf eye": 1} }, mead: { effect: "Frost resistance", duration: 600, cooldown: 600 } },
  { name: "Mead of Troll endurance", biome: "Swamp", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Trollfish": 2, "Honey": 10, "Powdered dragon eggshells": 1} }, mead: { effect: "+250 carry weight", duration: 300, cooldown: 120 } },
  { name: "Medium healing mead", biome: "Swamp", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Bloodbag": 4, "Raspberries": 10, "Dandelion": 1} }, mead: { effect: "75 health over 10 s", duration: 10, cooldown: 120 } },
  { name: "Tonic of Ratatosk", biome: "Swamp", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Blueberries": 10, "Cured squirrel hamstring": 1} }, mead: { effect: "+15 % walk and run speed, +7,5 % swim speed", duration: 600, cooldown: 0 } },
  { name: "Cooked wolf meat", biome: "Mountain", recipe: { station: "Cooking station", yield: 1, materials: {"Wolf meat": 1} }, food: { health: 45, stamina: 15, eitr: 0, healing: 3, duration: 1200 } },
  { name: "Eyescream", biome: "Mountain", recipe: { station: "Cauldron (3)", yield: 1, materials: {"Greydwarf eye": 3, "Freeze gland": 1} }, food: { health: 21, stamina: 65, eitr: 0, healing: 1, duration: 1500 } },
  { name: "Hearty Mountain logger's stew", biome: "Mountain", recipe: { station: "Food preparation table", yield: 1, materials: {"Wolf skewer": 2, "Onion soup": 3, "Carrot": 4, "Mountain peak pepper powder": 1} }, food: { health: 45, stamina: 45, eitr: 0, healing: 3, duration: 3000, feast: true } },
  { name: "Onion", biome: "Mountain", source: "Grow from Onion seeds (chests in Mountain ruins)", food: { health: 13, stamina: 40, eitr: 0, healing: 1, duration: 900 } },
  { name: "Onion soup", biome: "Mountain", recipe: { station: "Cauldron (2)", yield: 1, materials: {"Onion": 3} }, food: { health: 20, stamina: 60, eitr: 0, healing: 1, duration: 1200 } },
  { name: "Wolf jerky", biome: "Mountain", recipe: { station: "Cauldron (3)", yield: 2, materials: {"Wolf meat": 1, "Honey": 1} }, food: { health: 33, stamina: 33, eitr: 0, healing: 3, duration: 1800 } },
  { name: "Wolf skewer", biome: "Mountain", recipe: { station: "Cauldron (3)", yield: 1, materials: {"Wolf meat": 1, "Mushroom": 2, "Onion": 1} }, food: { health: 65, stamina: 21, eitr: 0, healing: 3, duration: 1500 } },
  { name: "Fragrant bundle", biome: "Mountain", source: "The Bog Witch, 140 coins for 5, after Moder" },
  { name: "Freeze gland", biome: "Mountain", source: "Drake" },
  { name: "Mountain peak pepper powder", biome: "Mountain", source: "The Bog Witch (coins)" },
  { name: "Toadstool", biome: "Mountain", source: "The Bog Witch, 85 coins, after Moder" },
  { name: "Wolf meat", biome: "Mountain", source: "Wolf" },
  { name: "Berserkir mead", biome: "Mountain", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Mushroom": 10, "Yellow mushroom": 10, "Toadstool": 1} }, mead: { effect: "Attack, block and dodge stamina -80 %, x1,5 damage taken", duration: 20, cooldown: 120 } },
  { name: "Brew of animal whispers", biome: "Mountain", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Onion": 5, "Carrot": 10, "Pungent pebbles": 1} }, mead: { effect: "x2 taming speed", duration: 600, cooldown: 0 } },
  { name: "Blood pudding", biome: "Plains", recipe: { station: "Cauldron (4)", yield: 1, materials: {"Thistle": 2, "Bloodbag": 2, "Barley flour": 4} }, food: { health: 25, stamina: 75, eitr: 0, healing: 2, duration: 1800 } },
  { name: "Bread", biome: "Plains", recipe: { station: "Food preparation table + Stone oven", yield: 2, materials: {"Bread dough": 1} }, food: { health: 23, stamina: 70, eitr: 0, healing: 2, duration: 1500 } },
  { name: "Cloudberries", biome: "Plains", source: "Bushes", food: { health: 13, stamina: 40, eitr: 0, healing: 1, duration: 900 } },
  { name: "Cooked chicken meat", biome: "Plains", recipe: { station: "Iron cooking station", yield: 1, materials: {"Chicken meat": 1} }, food: { health: 60, stamina: 20, eitr: 0, healing: 5, duration: 1200 } },
  { name: "Cooked egg", biome: "Plains", recipe: { station: "Cauldron (1)", yield: 1, materials: {"Egg": 1} }, food: { health: 35, stamina: 12, eitr: 0, healing: 2, duration: 1200 } },
  { name: "Cooked lox meat", biome: "Plains", recipe: { station: "Iron cooking station", yield: 1, materials: {"Lox meat": 1} }, food: { health: 50, stamina: 16, eitr: 0, healing: 4, duration: 1200 } },
  { name: "Fish wraps", biome: "Plains", recipe: { station: "Cauldron (4)", yield: 1, materials: {"Cooked fish": 2, "Barley flour": 4} }, food: { health: 70, stamina: 23, eitr: 0, healing: 4, duration: 1500 } },
  { name: "Frosted sweetbread", biome: "Plains", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Unbaked sweetbread": 1} }, food: { health: 43, stamina: 43, eitr: 0, healing: 2, duration: 1800 } },
  { name: "Lox meat pie", biome: "Plains", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Barley flour": 4, "Cloudberries": 2, "Lox meat": 2} }, food: { health: 75, stamina: 24, eitr: 0, healing: 4, duration: 1800 } },
  { name: "Plains pie picnic", biome: "Plains", recipe: { station: "Food preparation table", yield: 1, materials: {"Bread": 3, "Lox meat pie": 2, "Cloudberries": 5, "Grasslands herbalist harvest": 1} }, food: { health: 55, stamina: 55, eitr: 0, healing: 4, duration: 3000, feast: true } },
  { name: "Barley", biome: "Plains", source: "Fuling villages, then grow from Barley" },
  { name: "Barley flour", biome: "Plains", recipe: { station: "Windmill", yield: 1, materials: {"Barley": 1} } },
  { name: "Bread dough", biome: "Plains", recipe: { station: "Food preparation table", yield: 2, materials: {"Barley flour": 10} } },
  { name: "Chicken meat", biome: "Plains", source: "Hen (hatched from Eggs)" },
  { name: "Egg", biome: "Plains", source: "Haldor (1500 coins after Yagluth), then Hens" },
  { name: "Grasslands herbalist harvest", biome: "Plains", source: "The Bog Witch (coins)" },
  { name: "Grouper", biome: "Plains", source: "Fishing off Plains coasts" },
  { name: "Lox meat", biome: "Plains", source: "Lox" },
  { name: "Unbaked sweetbread", biome: "Plains", recipe: { station: "Food preparation table", yield: 2, materials: {"Cloudberries": 2, "Egg": 1, "Barley flour": 1, "Honey": 1} } },
  { name: "Anti-sting concoction", biome: "Plains", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Cloudberries": 10, "Grouper": 3, "Fragrant bundle": 1} }, mead: { effect: "Deathsquitos ignore you", duration: 600, cooldown: 0 } },
  { name: "Fire resistance barley wine", biome: "Plains", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Barley": 10, "Cloudberries": 10} }, mead: { effect: "Fire resistance", duration: 600, cooldown: 600 } },
  { name: "Medium stamina mead", biome: "Plains", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Cloudberries": 10, "Yellow mushroom": 10} }, mead: { effect: "160 stamina", duration: 2, cooldown: 120 } },
  { name: "Cooked hare meat", biome: "Mistlands", recipe: { station: "Iron cooking station", yield: 1, materials: {"Hare meat": 1} }, food: { health: 60, stamina: 20, eitr: 0, healing: 5, duration: 1200 } },
  { name: "Cooked seeker meat", biome: "Mistlands", recipe: { station: "Iron cooking station", yield: 1, materials: {"Seeker meat": 1} }, food: { health: 60, stamina: 20, eitr: 0, healing: 5, duration: 1200 } },
  { name: "Fish 'n' bread", biome: "Mistlands", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Anglerfish": 1, "Bread dough": 2} }, food: { health: 30, stamina: 90, eitr: 0, healing: 3, duration: 1800 } },
  { name: "Honey glazed chicken", biome: "Mistlands", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Chicken meat": 1, "Honey": 3, "Jotun puffs": 2} }, food: { health: 80, stamina: 26, eitr: 0, healing: 5, duration: 1800 } },
  { name: "Jotun puffs", biome: "Mistlands", source: "Ground, plantable", food: { health: 25, stamina: 25, eitr: 0, healing: 1, duration: 900 } },
  { name: "Magecap", biome: "Mistlands", source: "Ground, plantable", food: { health: 25, stamina: 25, eitr: 25, healing: 1, duration: 900 } },
  { name: "Meat platter", biome: "Mistlands", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Seeker meat": 1, "Lox meat": 1, "Hare meat": 1} }, food: { health: 80, stamina: 26, eitr: 0, healing: 5, duration: 1800 } },
  { name: "Misthare supreme", biome: "Mistlands", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Hare meat": 1, "Jotun puffs": 3, "Carrot": 2} }, food: { health: 85, stamina: 28, eitr: 0, healing: 5, duration: 1500 } },
  { name: "Mushroom omelette", biome: "Mistlands", recipe: { station: "Cauldron (5)", yield: 1, materials: {"Egg": 3, "Jotun puffs": 3} }, food: { health: 28, stamina: 85, eitr: 0, healing: 3, duration: 1500 } },
  { name: "Mushrooms galore á la Mistlands", biome: "Mistlands", recipe: { station: "Food preparation table", yield: 1, materials: {"Misthare supreme": 1, "Cooked seeker meat": 3, "Yggdrasil porridge": 1, "Herbs of the hidden hills": 1} }, food: { health: 65, stamina: 65, eitr: 33, healing: 5, duration: 3000, feast: true } },
  { name: "Salad", biome: "Mistlands", recipe: { station: "Cauldron (5)", yield: 1, materials: {"Jotun puffs": 3, "Onion": 3, "Cloudberries": 3} }, food: { health: 26, stamina: 80, eitr: 0, healing: 3, duration: 1500 } },
  { name: "Seeker aspic", biome: "Mistlands", recipe: { station: "Cauldron (5)", yield: 2, materials: {"Seeker meat": 2, "Magecap": 2, "Royal jelly": 2} }, food: { health: 28, stamina: 14, eitr: 85, healing: 3, duration: 1800 } },
  { name: "Stuffed mushroom", biome: "Mistlands", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Magecap": 3, "Blood clot": 1, "Turnip": 2} }, food: { health: 25, stamina: 12, eitr: 75, healing: 3, duration: 1500 } },
  { name: "Yggdrasil porridge", biome: "Mistlands", recipe: { station: "Cauldron (5)", yield: 1, materials: {"Sap": 4, "Barley": 3, "Royal jelly": 2} }, food: { health: 27, stamina: 13, eitr: 80, healing: 3, duration: 1500 } },
  { name: "Anglerfish", biome: "Mistlands", source: "Fishing off Mistlands coasts, Misty fishing bait" },
  { name: "Blood clot", biome: "Mistlands", source: "Tick" },
  { name: "Hare meat", biome: "Mistlands", source: "Hare" },
  { name: "Herbs of the hidden hills", biome: "Mistlands", source: "The Bog Witch (coins)" },
  { name: "Royal jelly", biome: "Mistlands", source: "Seeker broods, piles in Infested Mines" },
  { name: "Sap", biome: "Mistlands", source: "Sap extractor on Yggdrasil roots" },
  { name: "Scale hide", biome: "Mistlands", source: "Hare" },
  { name: "Seeker meat", biome: "Mistlands", source: "Seeker" },
  { name: "Lightfoot mead", biome: "Mistlands", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Scale hide": 2, "Feathers": 5, "Magecap": 5} }, mead: { effect: "-30 % jump stamina, +20 % jump height", duration: 600, cooldown: 0 } },
  { name: "Lingering stamina mead", biome: "Mistlands", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Sap": 10, "Cloudberries": 10, "Jotun puffs": 10} }, mead: { effect: "+25 % stamina regen", duration: 300, cooldown: 300 } },
  { name: "Major healing mead", biome: "Mistlands", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Blood clot": 4, "Royal jelly": 5} }, mead: { effect: "125 health over 10 s", duration: 10, cooldown: 120 } },
  { name: "Minor eitr mead", biome: "Mistlands", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Honey": 10, "Sap": 5, "Jotun puffs": 2, "Magecap": 5} }, mead: { effect: "125 eitr over 10 s", duration: 10, cooldown: 120 } },
  { name: "Ashlands gourmet bowl", biome: "Ashlands", recipe: { station: "Food preparation table", yield: 1, materials: {"Cooked asksvin tail": 3, "Vineberry cluster": 5, "Scorching medley": 2, "Fiery spice powder": 1} }, food: { health: 75, stamina: 75, eitr: 38, healing: 6, duration: 3000, feast: true } },
  { name: "Cooked asksvin tail", biome: "Ashlands", recipe: { station: "Iron cooking station", yield: 1, materials: {"Asksvin tail": 1} }, food: { health: 70, stamina: 24, eitr: 0, healing: 6, duration: 1200 } },
  { name: "Cooked bonemaw meat", biome: "Ashlands", recipe: { station: "Iron cooking station", yield: 1, materials: {"Bonemaw meat": 1} }, food: { health: 90, stamina: 30, eitr: 0, healing: 6, duration: 1500 } },
  { name: "Cooked volture meat", biome: "Ashlands", recipe: { station: "Iron cooking station", yield: 1, materials: {"Volture meat": 1} }, food: { health: 70, stamina: 24, eitr: 0, healing: 6, duration: 1200 } },
  { name: "Fiddlehead", biome: "Ashlands", source: "Ground", food: { health: 30, stamina: 30, eitr: 0, healing: 1, duration: 900 } },
  { name: "Fiery svinstew", biome: "Ashlands", recipe: { station: "Cauldron (5)", yield: 1, materials: {"Asksvin tail": 1, "Vineberry cluster": 2, "Smoke puff": 1} }, food: { health: 95, stamina: 32, eitr: 0, healing: 6, duration: 1500 } },
  { name: "Marinated greens", biome: "Ashlands", recipe: { station: "Cauldron (6)", yield: 1, materials: {"Sap": 3, "Magecap": 2, "Fiddlehead": 2, "Smoke puff": 2} }, food: { health: 32, stamina: 16, eitr: 95, healing: 4, duration: 1800 } },
  { name: "Mashed meat", biome: "Ashlands", recipe: { station: "Cauldron (6)", yield: 1, materials: {"Asksvin tail": 1, "Volture meat": 1, "Fiddlehead": 1} }, food: { health: 100, stamina: 34, eitr: 0, healing: 6, duration: 1500 } },
  { name: "Piquant pie", biome: "Ashlands", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Asksvin tail": 2, "Vineberry cluster": 2, "Barley flour": 4} }, food: { health: 105, stamina: 35, eitr: 0, healing: 6, duration: 1800 } },
  { name: "Roasted crust pie", biome: "Ashlands", recipe: { station: "Food preparation table + Stone oven", yield: 1, materials: {"Volture egg": 1, "Vineberry cluster": 2, "Barley flour": 4} }, food: { health: 34, stamina: 100, eitr: 0, healing: 4, duration: 1800 } },
  { name: "Scorching medley", biome: "Ashlands", recipe: { station: "Cauldron (6)", yield: 3, materials: {"Jotun puffs": 3, "Onion": 3, "Fiddlehead": 3} }, food: { health: 32, stamina: 95, eitr: 0, healing: 4, duration: 1500 } },
  { name: "Sizzling berry broth", biome: "Ashlands", recipe: { station: "Cauldron (5)", yield: 1, materials: {"Sap": 3, "Vineberry cluster": 2, "Fiddlehead": 2} }, food: { health: 28, stamina: 14, eitr: 85, healing: 4, duration: 1500 } },
  { name: "Smoke puff", biome: "Ashlands", source: "Ground", food: { health: 15, stamina: 15, eitr: 0, healing: 1, duration: 900 } },
  { name: "Sparkling shroomshake", biome: "Ashlands", recipe: { station: "Cauldron (6)", yield: 1, materials: {"Sap": 4, "Magecap": 2, "Vineberry cluster": 2, "Smoke puff": 2} }, food: { health: 30, stamina: 15, eitr: 90, healing: 4, duration: 1500 } },
  { name: "Spicy marmalade", biome: "Ashlands", recipe: { station: "Cauldron (5)", yield: 1, materials: {"Vineberry cluster": 3, "Honey": 1, "Fiddlehead": 1} }, food: { health: 30, stamina: 90, eitr: 0, healing: 4, duration: 1500 } },
  { name: "Vineberry cluster", biome: "Ashlands", source: "Vines, plantable from Vineberry seeds", food: { health: 30, stamina: 30, eitr: 30, healing: 1, duration: 900 } },
  { name: "Asksvin tail", biome: "Ashlands", source: "Asksvin" },
  { name: "Bonemaw meat", biome: "Ashlands", source: "Bonemaw serpent" },
  { name: "Fiery spice powder", biome: "Ashlands", source: "The Bog Witch (coins)" },
  { name: "Volture egg", biome: "Ashlands", source: "Volture nests, Volture" },
  { name: "Volture meat", biome: "Ashlands", source: "Volture" },
  { name: "Lingering eitr mead", biome: "Ashlands", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Sap": 10, "Vineberry cluster": 10, "Magecap": 10} }, mead: { effect: "+25 % eitr regen", duration: 300, cooldown: 300 } },
  { name: "Lingering healing mead", biome: "Ashlands", recipe: { station: "Mead ketill + Fermenter", yield: 6, materials: {"Sap": 10, "Vineberry cluster": 10, "Smoke puff": 10} }, mead: { effect: "+25 % health regen", duration: 300, cooldown: 300 } },
  { name: "Baked Poteitr", biome: "Deep North", recipe: { station: "Cauldron (7) + Stone oven", yield: 1, materials: {"Seal blubber": 1, "Kale": 2, "Poteitr": 1, "Oat flour": 2} }, food: { health: 34, stamina: 17, eitr: 100, healing: 5, duration: 1500 } },
  { name: "Cooked Moose Meat", biome: "Deep North", recipe: { station: "Iron cooking station", yield: 1, materials: {"Moose meat": 1} }, food: { health: 80, stamina: 27, eitr: 0, healing: 5, duration: 1200 } },
  { name: "Cooked Seal Blubber", biome: "Deep North", recipe: { station: "Stone oven", yield: 1, materials: {"Seal blubber": 1} }, food: { health: 60, stamina: 20, eitr: 0, healing: 5, duration: 1200 } },
  { name: "Fish Soup", biome: "Deep North", recipe: { station: "Cauldron (7)", yield: 1, materials: {"Raw fish": 3, "Kale": 2, "Ice": 2} }, food: { health: 37, stamina: 18, eitr: 105, healing: 5, duration: 1800 } },
  { name: "Kale", biome: "Deep North", source: "Grow from Kale seeds", food: { health: 35, stamina: 35, eitr: 0, healing: 1, duration: 900 } },
  { name: "Kale Chips", biome: "Deep North", recipe: { station: "Stone oven", yield: 1, materials: {"Kale": 12} }, food: { health: 35, stamina: 105, eitr: 0, healing: 5, duration: 1500, unverified: "Wiki gives Kale x12 at the Stone oven; the Raw Kale Chips step and yield are unconfirmed." } },
  { name: "Lingonberries", biome: "Deep North", source: "Bushes", food: { health: 35, stamina: 35, eitr: 0, healing: 1, duration: 900 } },
  { name: "Lingonberry Juice", biome: "Deep North", recipe: { station: "Cauldron (7)", yield: 1, materials: {"Lingonberries": 5, "Ice": 5} }, food: { health: 35, stamina: 105, eitr: 0, healing: 5, duration: 1500 } },
  { name: "Luminous Larva", biome: "Deep North", source: "Walls in the Winding Tunnels", food: { health: 30, stamina: 30, eitr: 0, healing: 1, duration: 900 } },
  { name: "Meat In Bread", biome: "Deep North", recipe: { station: "Cauldron (7)", yield: 2, materials: {"Moose meat": 1, "Kale": 2, "Oat flour": 1, "Lingonberries": 2} }, food: { health: 110, stamina: 37, eitr: 0, healing: 7, duration: 1800 } },
  { name: "Meatballs and Poteitr", biome: "Deep North", recipe: { station: "Cauldron (7)", yield: 1, materials: {"Moose meat": 1, "Poteitr": 2, "Lingonberries": 2} }, food: { health: 35, stamina: 18, eitr: 105, healing: 5, duration: 1500 } },
  { name: "Northern Morning Fare", biome: "Deep North", recipe: { station: "Food preparation table", yield: 1, materials: {"Cooked Moose Meat": 3, "Poteitr": 5, "Oat flour": 2, "Seasoning of the Gourd": 1} }, food: { health: 85, stamina: 85, eitr: 43, healing: 7, duration: 3000, feast: true } },
  { name: "Oat Milk", biome: "Deep North", recipe: { station: "Mead ketill", yield: 1, materials: {"Oats": 5, "Ice": 5} }, food: { health: 37, stamina: 110, eitr: 0, healing: 5, duration: 1500 } },
  { name: "Oatmeal", biome: "Deep North", recipe: { station: "Cauldron (6)", yield: 1, materials: {"Oats": 2, "Lingonberries": 2, "Oat Milk": 1} }, food: { health: 39, stamina: 115, eitr: 85, healing: 5, duration: 1800, unverified: "Wiki lists 39/115/85, total 239, far above every other food. Not seen in game yet." } },
  { name: "Oats", biome: "Deep North", source: "Grow from Oat seeds", food: { health: 33, stamina: 33, eitr: 0, healing: 3, duration: 1800 } },
  { name: "Oven Pancake", biome: "Deep North", recipe: { station: "Cauldron (6) + Stone oven", yield: 1, materials: {"Moose meat": 1, "Lingonberries": 2, "Poteitr": 1, "Oat flour": 2} }, food: { health: 39, stamina: 115, eitr: 0, healing: 5, duration: 1500 } },
  { name: "Pancakes", biome: "Deep North", recipe: { station: "Cauldron (6)", yield: 3, materials: {"Blueberries": 2, "Egg": 2, "Oat Milk": 1, "Oat flour": 2} }, food: { health: 39, stamina: 115, eitr: 0, healing: 5, duration: 1800 } },
  { name: "Poteitr", biome: "Deep North", source: "Grow from Seed Poteitr", food: { health: 35, stamina: 35, eitr: 35, healing: 1, duration: 900 } },
  { name: "Seal Meat Soup", biome: "Deep North", recipe: { station: "Cauldron (7)", yield: 1, materials: {"Seal blubber": 2, "Kale": 2, "Ice": 2} }, food: { health: 110, stamina: 37, eitr: 0, healing: 7, duration: 1800 } },
  { name: "Smoked Fish", biome: "Deep North", recipe: { station: "Cauldron (7)", yield: 1, materials: {"Raw fish": 1, "Kale": 1, "Poteitr": 1} }, food: { health: 30, stamina: 16, eitr: 95, healing: 5, duration: 1500 } },
  { name: "Smoked Moose Meat", biome: "Deep North", recipe: { station: "Cauldron (7)", yield: 1, materials: {"Moose meat": 1, "Kale": 2} }, food: { health: 105, stamina: 35, eitr: 0, healing: 7, duration: 1500 } },
  { name: "Ice", biome: "Deep North", source: "Ice sheets and ponds" },
  { name: "Moose meat", biome: "Deep North", source: "Moose" },
  { name: "Oat flour", biome: "Deep North", recipe: { station: "Windmill", yield: 1, materials: {"Oats": 1} }, unverified: "Windmill recipe assumed 1 Oats to 1 Oat Flour like Barley flour. Unconfirmed." },
  { name: "Seal blubber", biome: "Deep North", source: "Seal" },
  { name: "Seasoning of the Gourd", biome: "Deep North", source: "The Bog Witch (coins)" },
];
